### ISSUE TITLE
Hashrate Chart not working

### ISSUE THREAD

**Issue by pool2mine** [minerpoolcf/ethash-minerpool#6]
Hi, I installed this pool, evething is working fine except for the hash rate chart... am I missing something here? please let me know. Thanks!

**Comment by pool2mine** [comment]
Hi @duyk16, i saw you was the last one making changes to this repository. i can't get the charts to work, is there something that i'm doing wrong here? i am using the new api with the charts config but still not working. would you help me out here? thanks in advance!

**Comment by honorkeles** [comment]
@pool2mine hi, how did you make it work? I am just taking chart codes but I couldn't integrate it with the original sammy007's setup files.
